version: "3.9"

services:
  app:
    container_name: "plastic_api"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "127.0.0.1:8005:8000"
    env_file:
      - ./.env
    command: >
      /bin/sh -c "
      python manage.py migrate &&
      python manage.py init &&
      python manage.py runserver 0.0.0.0:8000
      "
    